knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            redirect_route: connect_service_check
            redirect_params: 
                service: google
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: connect_service_check
            redirect_params: 
                service: facebook
            graph_api_version: v8.0
        linkedin:
            type: linkedin
            client_id: '%env(OAUTH_LINKEDIN_ID)%'
            client_secret: '%env(OAUTH_LINKEDIN_SECRET)%'
            redirect_route: connect_service_check
            redirect_params: 
                service: linkedin
        instagram:
            type: instagram
            client_id: '%env(OAUTH_INSTAGRAM_ID)%'
            client_secret: '%env(OAUTH_INSTAGRAM_SECRET)%'
            redirect_route: connect_service_check
            redirect_params: 
                service: instagram
