# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        profile:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [128, 128], mode: outbound }
        account_profile:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [200, 200], mode: outbound }
        cover_small:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [370, 246], mode: outbound }
        banner:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [1920, 1024], mode: outbound }
        gallery:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [339, 230], mode: outbound }
        service:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 75], mode: outbound }
        category:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [263, 175], mode: outbound }
        category_art_small:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [310, 60], mode: outbound }
        small:
            quality: 80
            filters:
                relative_resize:
                    widen: 350

        # Shrink/upscale the image to 800px of height, with full quality
        big:
            filters:
                relative_resize:
                    heighten: 800
                    # Will allow smaller images to take 800px of height, 
                    # width will change accordingly since aspect ration is still valid.
                    allow_upscale: true 

