# OUR MAIN MENU
main_menu:
    design:
        menu:
            - { label: 'Accueil', route: 'app_home', icon: 'fa fa-home' }
            - { label: 'Menu 1', route: 'app_blog' }
            - label: 'Menu 2'
              children:
                - label: 'Menu 21'
                  cssClass: 'col-lg-6'
                  children:
                    - { label: 'Menu 211', route: 'app_blog' }
                    - { label: 'Menu 212', route: 'app_blog' }
                - label: 'Menu 22'
                  cssClass: 'col-lg-6'
                  children:
                    - { label: 'Menu 221', route: 'app_blog' }
                    - { label: 'Menu 222', route: 'app_blog' }
                - label: 'Menu 23'
                  cssClass: 'col-lg-6'
                  children:
                    - { label: 'Menu 231', route: 'app_blog' }
                    - { label: 'Menu 232', route: 'app_blog' }
                - label: 'Menu 24'
                  cssClass: 'col-lg-6'
                  children:
                    - { label: 'Menu 241', route: 'app_blog' }
                    - { label: 'Menu 242', route: 'app_blog' }
            - { label: 'Menu 3', route: 'app_blog' }
            - { label: 'Blog', route: 'app_blog'}

               