twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        website_title: '%app_website_title%'
        my_app: '@App\Twig\AppExtension' 
        locales: '%app_locales%'

when@test:
    twig:
        strict_variables: true
