vich_uploader:
    db_driver: orm

    mappings:
        social_media_images:
            uri_prefix: '%app.path.social_media_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.social_media_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
