vich_uploader:
    db_driver: orm

    mappings:
        social_media_images:
            uri_prefix: '%app.path.social_media_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.social_media_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
            delete_on_remove: false
        category_pro_images:
            uri_prefix: '%app.path.category_pro_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.category_pro_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        professional_images:
            uri_prefix: '%app.path.professional_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.professional_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        professional_video:
            uri_prefix: '%app.path.professional_video%'
            upload_destination: '%kernel.project_dir%/public%app.path.professional_video%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        service_images:
            uri_prefix: '%app.path.service_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.service_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
            delete_on_remove: false
        banner_images:
            uri_prefix: '%app.path.banner_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.banner_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        category_art_images:
            uri_prefix: '%app.path.category_art_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.category_art_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        article_images:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
