vich_uploader:
    db_driver: orm

    mappings:
        social_media_images:
            uri_prefix: '%app.path.social_media_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.social_media_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
            delete_on_remove: false
        professional_images:
            uri_prefix: '%app.path.professional_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.professional_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        service_images:
            uri_prefix: '%app.path.service_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.service_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
            delete_on_remove: false
