app_home:
    path: /
    controller: App\Controller\Front\HomeController::index
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
app_admin_login:
    path: /admin/login
    controller: App\Controller\Admin\SecurityController::login
app_admin_logout:
    path: /admin/logout
    controller: App\Controller\Admin\SecurityController::logout
app_login:
    path: /login
    controller: App\Controller\Front\SecurityController::login
    methods: POST
app_account:
    path: /account
    controller: App\Controller\Front\AccountController::index
app_logout:
    path: /logout
    controller: App\Controller\Front\SecurityController::logout
app_social_url:
    path: /social_url
    controller: App\Controller\Front\Partials\SocialUrlController::index
app_banner:
    path: /banner
    controller: App\Controller\Front\Partials\BannerController::index
app_main_menu:
    path: /main_menu
    controller: App\Controller\Front\Partials\MainMenuController::index
app_contact:
    path: /contact
    controller: App\Controller\Front\ContactController::index
app_blog:
    path: /blog
    controller: App\Controller\Front\BlogController::index
app_about:
    path: /about
    controller: App\Controller\Front\AboutController::index
app_professional:
    path: /professional
    controller: App\Controller\Front\ProfessionalController::show
app_category_pro:
    path: /professional/{slug}/category
    controller: App\Controller\Front\CategoryProController::show