#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout