#app_home:
    #path: /
    #controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    #defaults:
        #route: home
        #permanent: true
        #keepQueryParams: true
app_home:
    path: /
    controller: App\Controller\Front\HomeController::index
    #requirements:
        #_locale: '%app_locale%'
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
admin_exchange:
    path: /admin/exchange
    controller: App\Controller\Admin\ExchangeController::index
admin_exchange_message:
    path: /admin/{id}/exchange
    controller: App\Controller\Admin\ExchangeController::message
    requirements:
        id: '\d+'
app_admin_login:
    path: /admin/login
    controller: App\Controller\Admin\SecurityController::login
app_admin_logout:
    path: /admin/logout
    controller: App\Controller\Admin\SecurityController::logout
app_login:
    path: /login
    controller: App\Controller\Front\SecurityController::login
    methods: POST|GET
    #requirements:
        #_locale: '%app_locale%'
app_login_api:
    path: /api/v1/login
    controller: App\Controller\Front\SecurityController::apilogin
    methods: POST
connect_google_start:
    path: /connect/google
    controller: App\Controller\Front\SecurityController::google
connect_facebook_start:
    path: /connect/facebook
    controller: App\Controller\Front\SecurityController::facebook
connect_linkedin_start:
    path: /connect/linkedin
    controller: App\Controller\Front\SecurityController::linkedin
connect_github_start:
    path: /connect/github
    controller: App\Controller\Front\SecurityController::github
connect_service_check:
    path: /connect/{service}/check
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
app_register:
    path: /register
    controller: App\Controller\Front\RegistrationController::register
    methods: POST|GET
    #requirements:
        #_locale: '%app_locale%'
app_activation:
    path: /activation/{token}
    controller: App\Controller\Front\RegistrationController::activation
    methods: GET
app_account:
    path: /account/information
    controller: App\Controller\Front\AccountController::index
app_account_password:
    path: /account/password
    controller: App\Controller\Front\AccountController::password
app_account_need:
    path: /account/need
    controller: App\Controller\Front\AccountController::need
app_account_coordonnee:
    path: /account/coordonnee
    controller: App\Controller\Front\AccountController::coordonnee
app_account_conversation:
    path: /account/conversation
    controller: App\Controller\Front\AccountController::conversation
app_account_favoris:
    path: /account/favoris
    controller: App\Controller\Front\AccountController::favoris
app_account_message:
    path: /account/{id}/conversation
    controller: App\Controller\Front\AccountController::message
app_account_professional_information:
    path: /account/information/professional
    controller: App\Controller\Front\AccountController::information
app_account_professional_social:
    path: /account/social/professional
    controller: App\Controller\Front\AccountController::social
app_account_professional_service:
    path: /account/service/professional
    controller: App\Controller\Front\AccountController::service
app_account_professional_training:
    path: /account/training/professional
    controller: App\Controller\Front\AccountController::training
app_account_professional_reference:
    path: /account/reference/professional
    controller: App\Controller\Front\AccountController::reference
app_account_professional_proposal:
    path: /account/proposal/professional
    controller: App\Controller\Front\AccountController::proposal
app_account_notification:
    path: /account/notification
    controller: App\Controller\Front\AccountController::notification
app_account_notification_show:
    path: /account/{id}/notification
    controller: App\Controller\Front\NeedController::notification
    requirements:
        id: '\d+'
app_account_professional_proposal_edit:
    path: /account/proposal/professional/{id}/edit
    controller: App\Controller\Front\AccountController::editproposal
    requirements:
        id: '\d+'
app_account_professional_proposal_show:
    path: /account/proposal/professional/{id}/show
    controller: App\Controller\Front\AccountController::showproposal
    requirements:
        id: '\d+'
app_account_professional_need_proposal:
    path: /account/need/{id}/proposal
    controller: App\Controller\Front\AccountController::proposalneed
    requirements:
        id: '\d+'
app_account_professional_proposal_delete:
    path: /account/proposal/professional/{id}/delete
    controller: App\Controller\Front\AccountController::deleteproposal
    requirements:
        id: '\d+'
app_account_professional_gallery:
    path: /account/gallery/professional
    controller: App\Controller\Front\AccountController::gallery
app_account_professional_option:
    path: /account/option/professional
    controller: App\Controller\Front\AccountController::option
app_account_need_create:
    path: /account/need/create
    controller: App\Controller\Front\AccountController::createneed
app_account_need_show:
    path: /account/need/{id}/show
    controller: App\Controller\Front\AccountController::showneed
    requirements:
        id: '\d+'
app_account_need_edit:
    path: /account/need/{id}/edit
    controller: App\Controller\Front\AccountController::editneed
    requirements: 
        id: '\d+'
app_account_need_delete:
    path: account/need/{id}/delete
    controller: App\Controller\Front\AccountController::deleteneed
    requirements:
        id: '\d+'
app_account_need_re_publish:
    path: account/need/{id}/re-publish
    controller: App\Controller\Front\AccountController::republishneed
    requirements:
        id: '\d+'
app_logout:
    path: /logout
    controller: App\Controller\Front\SecurityController::logout
app_contact:
    path: /contact
    controller: App\Controller\Front\ContactController::index
    #requirements:
        #_locale: '%app_locale%'
app_blog:
    path: /blog
    controller: App\Controller\Front\BlogController::index
app_tariff:
    path: /tariff
    controller: App\Controller\Front\TariffController::index
    #requirements:
        #_locale: '%app_locale%'
app_blog_article:
    path: /blog/{slug}/article
    controller: App\Controller\Front\BlogController::show
    #requirements:
        #_locale: '%app_locale%'
app_blog_search:
    path: /blog/article/search
    controller: App\Controller\Front\BlogController::search
    #requirements:
        #_locale: '%app_locale%'
app_blog_category:
    path: /blog/article/{slug}/category
    controller: App\Controller\Front\BlogController::category
    #requirements:
        #_locale: '%app_locale%'
app_about:
    path: /about
    controller: App\Controller\Front\AboutController::index
    #requirements:
        #_locale: '%app_locale%'
app_professional:
    path: /professional
    controller: App\Controller\Front\ProfessionalController::index
    #requirements:
        #_locale: '%app_locale%'
app_professional_show:
    path: /professional/{id}/{slug}/show
    controller: App\Controller\Front\ProfessionalController::show
    requirements:
        id: '\d+'
app_professional_new:
    path: /professional/new
    controller: App\Controller\Front\ProfessionalController::new
    #requirements:
        #_locale: '%app_locale%'
app_professional_create:
    path: /professional/create
    controller: App\Controller\Front\ProfessionalController::create
    #requirements:
        #_locale: '%app_locale%'
app_professional_search:
    path: /professional/search
    controller: App\Controller\Front\ProfessionalController::search
    #requirements:
        #_locale: '%app_locale%'
app_professional_vip:
    path: /professional/vip
    controller: App\Controller\Front\ProfessionalController::vip
    #requirements:
        #_locale: '%app_locale%'
app_professional_like:
    path: /professional/{id}/{slug}/like
    controller: App\Controller\Front\ProfessionalController::like
    requirements:
        id: '\d+'
app_professional_gallery:
    path: /professional/gallery/edit
    controller: App\Controller\Front\ProfessionalController::gallery
    #requirements:
        #_locale: '%app_locale%'
app_professional_gallery_image_delete:
    path: /professional/gallery/{id}/delete
    controller: App\Controller\Front\ProfessionalController::deleteImage
    methods: DELETE
    requirements:
        id: '\d+'
app_professional_gallery_image_edit:
    path: /professional/gallery/ajax/edit
    controller: App\Controller\Front\ProfessionalController::editImage
    methods: POST
app_professional_gallery_image:
    path: /professional/gallery/{id}/show
    controller: App\Controller\Front\ProfessionalController::getImage
    methods: GET
    requirements:
        id: '\d+'
app_professional_area:
    path: /professional/index
    controller: App\Controller\Front\ProfessionalController::index
app_professional_ajax:
    path: /professional/ajax
    controller: App\Controller\Front\ProfessionalController::displayAjax
    methods: GET|POST
app_category_pro:
    path: /professional/{slug}/category
    controller: App\Controller\Front\CategoryProController::show
    #requirements:
        #_locale: '%app_locale%'
app_category_popular:
    path: /professional/category/popular
    controller: App\Controller\Front\CategoryProController::popular
    #requirements:
        #_locale: '%app_locale%'
app_change_locale:
    path: /application/{locale}/edit
    controller: App\Controller\Front\HomeController::changeLocale
app_forgotten_password:
    path: /forgotten-pass
    controller: App\Controller\Front\SecurityController::forgottenPass
app_reset_password:
    path: /{token}/reset-pass
    controller: App\Controller\Front\SecurityController::resetPass
app_professional_need:
    path: professional/need
    controller: App\Controller\Front\NeedController::index
app_professional_need_create:
    path: professional/need/create
    controller: App\Controller\Front\NeedController::create
app_professional_need_show:
    path: professional/{id}/need
    controller: App\Controller\Front\NeedController::show
    requirements:
        id: '\d+'
app_professional_proposal:
    path: professional/proposal/{id}/need
    controller: App\Controller\Front\NeedController::proposal
app_professional_proposal_nature:
    path: professional/proposal/{id}/nature/{nature}
    controller: App\Controller\Front\NeedController::nature
    requirements:
        id: '\d+'
app_profile:
    path: /{id}/{slug}/profile
    controller: App\Controller\Front\AccountController::profile
app_professional_proposal_create:
    path: professional/proposal/{id}/create
    controller: App\Controller\Front\NeedController::newproposal
    requirements:
        id: '\d+'