app_home:
    path: /
    controller: App\Controller\Front\HomeController::index
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
app_admin_login:
    path: /admin/login
    controller: App\Controller\Admin\SecurityController::login
app_admin_logout:
    path: /admin/logout
    controller: App\Controller\Admin\SecurityController::logout
app_login:
    path: /login
    controller: App\Controller\Front\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\Front\SecurityController::logout